# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state_control_msg.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'state_control_msg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17state_control_msg.proto\"\x1f\n\x07Vector2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"(\n\x08TimeSpec\x12\x0b\n\x03sec\x18\x01 \x01(\x04\x12\x0f\n\x07nanosec\x18\x02 \x01(\r\")\n\x06Header\x12\r\n\x05stamp\x18\x01 \x01(\x04\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\"5\n\x0bStateScalar\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\r\n\x05state\x18\x02 \x01(\x02\"@\n\x0cStateVector2\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x17\n\x05state\x18\x02 \x01(\x0b\x32\x08.Vector2\"@\n\x0cStateVector3\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x17\n\x05state\x18\x02 \x01(\x0b\x32\x08.Vector3\"\xdb\x01\n\x05State\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x1d\n\x06\x65\x66\x66ort\x18\x02 \x01(\x0b\x32\r.StateVector2\x12*\n\x13linear_acceleration\x18\x03 \x01(\x0b\x32\r.StateVector3\x12\'\n\x10\x61ngular_velocity\x18\x04 \x01(\x0b\x32\r.StateVector3\x12%\n\x0emagnetic_field\x18\x05 \x01(\x0b\x32\r.StateVector3\x12\x1e\n\x08\x64istance\x18\x06 \x01(\x0b\x32\x0c.StateScalar\"A\n\x07\x43ontrol\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x1d\n\x06\x65\x66\x66ort\x18\x02 \x01(\x0b\x32\r.StateVector2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_control_msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR2']._serialized_start=27
  _globals['_VECTOR2']._serialized_end=58
  _globals['_VECTOR3']._serialized_start=60
  _globals['_VECTOR3']._serialized_end=102
  _globals['_TIMESPEC']._serialized_start=104
  _globals['_TIMESPEC']._serialized_end=144
  _globals['_HEADER']._serialized_start=146
  _globals['_HEADER']._serialized_end=187
  _globals['_STATESCALAR']._serialized_start=189
  _globals['_STATESCALAR']._serialized_end=242
  _globals['_STATEVECTOR2']._serialized_start=244
  _globals['_STATEVECTOR2']._serialized_end=308
  _globals['_STATEVECTOR3']._serialized_start=310
  _globals['_STATEVECTOR3']._serialized_end=374
  _globals['_STATE']._serialized_start=377
  _globals['_STATE']._serialized_end=596
  _globals['_CONTROL']._serialized_start=598
  _globals['_CONTROL']._serialized_end=663
# @@protoc_insertion_point(module_scope)
